version: 2.1

jobs:
  artifact-browser-demo:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: Create a nested artifact bundle
          shell: /bin/bash -eo pipefail
          command: bash ./scripts/generate-circleci-artifacts-demo.sh
      - store_artifacts:
          path: /tmp/circleci-artifacts-demo
          destination: bulk-upload-demo

workflows:
  artifact-browser-demo-workflow:
    jobs:
      - artifact-browser-demo
